FROM ubuntu:14.04

# get nginx signing key
ADD http://nginx.org/keys/nginx_signing.key nginx_signing.key

# add nginx signing key
RUN apt-key add nginx_signing.key

# cleanup
RUN rm nginx_signing.key

# add nginx sources
RUN echo "deb http://nginx.org/packages/ubuntu/ trusty nginx" >> /etc/apt/sources.list
RUN echo "deb-src http://nginx.org/packages/ubuntu/ trusty nginx" >> /etc/apt/sources.list

RUN apt-get update && apt-get -y install \
    nginx \
    git

# now setup user : m flag creates home dir and s flag specifies shell
ENV USER cabinet-user
RUN useradd -ms /bin/bash $USER
RUN echo "$USER ALL = NOPASSWD : $(which nginx)" > /etc/sudoers.d/cabinet-user
ENV HOME /home/$USER

# finally, as root, configure the ssh daemon
RUN echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config

# setup deploy key for when cabinet repo will need to be cloned
RUN mkdir $HOME/.ssh
ADD deploy_key $HOME/.ssh/id_rsa
RUN chmod 600 $HOME/.ssh/id_rsa
RUN chmod 700 $HOME/.ssh

# pull in runtime script
ADD run-cabinet.sh $HOME/run-cabinet.sh

# fix ownership
RUN chown -R $USER:$USER $HOME

# set up nginx conf for cabinet
RUN echo "include $HOME/hwcentral-cabinet/devops/nginx.conf;" > /etc/nginx/nginx.conf

# set user and working dir
USER $USER
WORKDIR $HOME

EXPOSE 9878
CMD ["./run-cabinet.sh"]